/* Generated By:JJTree&JavaCC: Do not edit this line. AnnotationParserConstants.java */
/*******************************************************************************************
 * Copyright (c) Jonas Bonér, Alexandre Vasseur. All rights reserved.                      *
 * http://backport175.codehaus.org                                                         *
 * --------------------------------------------------------------------------------------- *
 * The software in this package is published under the terms of Apache License Version 2.0 *
 * a copy of which has been included with this distribution in the license.txt file.       *
 *******************************************************************************************/

package org.codehaus.backport175.compiler.parser.ast;

public interface AnnotationParserConstants {

  int EOF = 0;
  int DOT = 3;
  int INTEGER = 4;
  int HEXNUMBER = 5;
  int OCTNUMBER = 6;
  int DECIMAL_LITERAL = 7;
  int HEX_LITERAL = 8;
  int OCTAL_LITERAL = 9;
  int FLOAT = 10;
  int EXPONENT = 11;
  int BOOLEAN = 12;
  int STRING = 13;
  int CHAR = 14;
  int NEWLINE = 15;
  int LEFT_PARENTHEZIS = 16;
  int RIGHT_PARENTHEZIS = 17;
  int LEFT_BRACKET = 18;
  int RIGHT_BRACKET = 19;
  int COMMA = 20;
  int EQUALS = 21;
  int AT = 22;
  int ANNOTATION = 23;
  int JAVA_NAME = 24;
  int JAVA_TYPE_MAYBEARRAY = 25;
  int JAVA_TYPE = 26;
  int JAVA_LETTER = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\".\"",
    "<INTEGER>",
    "<HEXNUMBER>",
    "<OCTNUMBER>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT>",
    "<EXPONENT>",
    "<BOOLEAN>",
    "<STRING>",
    "<CHAR>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"=\"",
    "\"@\"",
    "<ANNOTATION>",
    "<JAVA_NAME>",
    "<JAVA_TYPE_MAYBEARRAY>",
    "<JAVA_TYPE>",
    "<JAVA_LETTER>",
    "\"\\r\\n\"",
  };

}
